CREATE TABLE [dbo].[UserNotes]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[ParentSeverityId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES SeverityMaster(Id),
	[Heading] NVARCHAR(256) NULL,
	[Content] NVARCHAR(1024) NULL,
    [CreatedDate] DATETIME NOT NULL,
	[ModifiedDate] DATETIME NOT NULL,
	CONSTRAINT PK_UserNotes PRIMARY KEY (Id),
	CONSTRAINT FK_UserNotes_SeverityMaster FOREIGN KEY (ParentSeverityId) REFERENCES SeverityMaster(Id)
)
